/**
 * v0.39.0 — postinstall instructions.md bootstrap helpers.
 *
 * Pure functions used by scripts/bootstrap-agents-md.mjs to append a
 * snippet of meta-governor [SYSTEM-NUDGE] directives to the user's
 * `~/.config/opencode/plugins/omo-meta-governor/instructions.md` on
 * `npm install`.
 *
 * Why this file exists:
 *   - The plugin runtime pushes its directives via `chat.system.transform`
 *     on every session that loads the plugin. That covers opencode-launched
 *     sessions and sub-agents spawned from opencode.
 *   - Sub-agents launched outside opencode (e.g. via a parent agent's
 *     `task()` tool) don't load the plugin, so they never see the runtime
 *     injection.
 *   - Writing the directives to `~/.config/opencode/plugins/omo-meta-governor/instructions.md`
 *     (registered via `opencode.jsonc` `instructions` array) makes them
 *     visible to every agent OpenCode spawns, regardless of how it loads.
 *
 * Idempotent: detects the marker comments and skips re-write.
 * Version-aware: upgrades in place when a newer version is installed.
 * Safe: never overwrites user content; appends after.
 * Opt-out: `OMO_META_GOVERNOR_NO_BOOTSTRAP=1` env var.
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { homedir } from "node:os";
import {
  MARKER_OPEN,
  MARKER_CLOSE,
  isInstalled,
  stripSnippet,
  installedVersion,
  buildInstructionsSnippet,
} from "./utils/instructions-md";
import { newPluginPaths, patchInstructionsArray } from "./utils/migrate";

export { MARKER_OPEN, MARKER_CLOSE, isInstalled, stripSnippet, installedVersion };
export { buildInstructionsSnippet as buildSnippet };

export const VERSION = "0.39.0";

function appendSnippet(existing: string, snippet: string): string {
  const trimmed = existing.replace(/\s+$/, "");
  return `${trimmed}\n\n${snippet}\n`;
}

/**
 * @deprecated since v0.39.0 — use mergeIntoInstructions for the new plugin path.
 * Kept for backward compat so existing tests importing `mergeInto` still pass.
 * Targets the old AGENTS.md file.
 */
export function mergeInto(existing: string, snippet: string, version: string): string {
  const existingVersion = installedVersion(existing);

  if (existingVersion === version) return existing;

  if (existingVersion !== null) {
    return appendSnippet(stripSnippet(existing), snippet);
  }

  if (!existing.trim()) {
    return [
      `# Auto-generated by @herjarsa/omo-meta-governor v${version}`,
      "# This file is read by opencode for every session. Edit freely.",
      "# The META-GOVERNOR snippet below is auto-managed by npm postinstall;",
      "# set OMO_META_GOVERNOR_NO_BOOTSTRAP=1 to disable re-installs.",
      "",
      snippet,
      "",
    ].join("\n");
  }

  return appendSnippet(existing, snippet);
}

/**
 * Returns merged content for the new `instructions.md` file:
 * - Same version already installed → return `existing` unchanged (idempotent).
 * - Different version installed → strip the old snippet, append the new one.
 * - No snippet installed → append snippet (preserving existing user content).
 * - File empty → header + snippet.
 */
export function mergeIntoInstructions(existing: string, snippet: string, version: string): string {
  const existingVersion = installedVersion(existing);

  if (existingVersion === version) return existing;

  if (existingVersion !== null) {
    return appendSnippet(stripSnippet(existing), snippet);
  }

  if (!existing.trim()) {
    return [
      `# Auto-generated by @herjarsa/omo-meta-governor v${version}`,
      "# Plugin instructions for OpenCode. Edit freely.",
      "# This file is auto-managed by npm postinstall; set OMO_META_GOVERNOR_NO_BOOTSTRAP=1 to disable.",
      "",
      snippet,
      "",
    ].join("\n");
  }

  return appendSnippet(existing, snippet);
}

/**
 * Default bootstrap: migrates old AGENTS.md snippet and writes new instructions.md.
 * Idempotent and non-fatal — never throws.
 */
export function bootstrap(): void {
  if (process.env.OMO_META_GOVERNOR_NO_BOOTSTRAP === "1") {
    console.log("[bootstrap] skipped (OMO_META_GOVERNOR_NO_BOOTSTRAP=1)");
    return;
  }
  try {
    // 1. Backward-compat: strip old snippet from AGENTS.md if present
    const oldAgentsPath = join(homedir(), ".config", "opencode", "AGENTS.md");
    try {
      if (existsSync(oldAgentsPath)) {
        const oldContent = readFileSync(oldAgentsPath, "utf-8");
        if (installedVersion(oldContent) !== null) {
          const stripped = stripSnippet(oldContent);
          writeFileSync(oldAgentsPath, stripped, "utf-8");
          console.log(`[bootstrap] stripped old snippet from ${oldAgentsPath}`);
        }
      }
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      console.error(`[bootstrap] warning: failed to strip AGENTS.md: ${msg}`);
    }

    // 2. Write new snippet to instructions.md
    const paths = newPluginPaths();
    try {
      mkdirSync(dirname(paths.instructions), { recursive: true });
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      console.error(`[bootstrap] warning: failed to create plugin dir: ${msg}`);
    }
    let existing = "";
    try {
      existing = existsSync(paths.instructions) ? readFileSync(paths.instructions, "utf-8") : "";
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      console.error(`[bootstrap] warning: failed to read instructions.md: ${msg}`);
      existing = "";
    }
    if (!isInstalled(existing, VERSION)) {
      const snippet = buildInstructionsSnippet(VERSION);
      const merged = mergeIntoInstructions(existing, snippet, VERSION);
      try {
        writeFileSync(paths.instructions, merged, "utf-8");
        if (installedVersion(existing)) {
          console.log(`[bootstrap] upgraded to v${VERSION} at ${paths.instructions}`);
        } else {
          console.log(`[bootstrap] wrote v${VERSION} snippet to ${paths.instructions}`);
        }
      } catch (err) {
        const msg = err instanceof Error ? err.message : String(err);
        console.error(`[bootstrap] failed to write instructions.md (non-fatal): ${msg}`);
      }
    } else {
      console.log(`[bootstrap] v${VERSION} snippet already present at ${paths.instructions}, skipping`);
    }

    // 3. Patch opencode.jsonc to include instructions.md
    try {
      const opencodeJsoncPath = join(homedir(), ".config", "opencode", "opencode.jsonc");
      const rel = "plugins/omo-meta-governor/instructions.md";
      const res = patchInstructionsArray(opencodeJsoncPath, rel);
      if (res.changed) {
        console.log(`[bootstrap] patched ${opencodeJsoncPath} to include ${rel}`);
      } else if (res.error) {
        // file not found is ok (opencode.jsonc optional); malformed is warning
        if (res.error !== "file not found") {
          console.error(`[bootstrap] warning: failed to patch opencode.jsonc: ${res.error}`);
        }
      }
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      console.error(`[bootstrap] warning: failed to patch opencode.jsonc: ${msg}`);
    }
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    console.error(`[bootstrap] failed (non-fatal): ${msg}`);
  }
}

export default bootstrap;
