/**
 * v0.38.9 — tests for the postinstall AGENTS.md bootstrap.
 *
 * Pure-function tests for the helpers used by scripts/bootstrap-agents-md.ts.
 * No I/O. No filesystem. No `homedir()` reads. The script itself (which
 * touches the real filesystem) is exercised manually, not via bun:test,
 * because writing to the user's actual ~/.config would be a side-effect
 * during the test run.
 */
import { describe, expect, it } from "bun:test"
import {
  MARKER_OPEN,
  MARKER_CLOSE,
  buildSnippet,
  installedVersion,
  isInstalled,
  mergeInto,
  stripSnippet,
} from "./bootstrap-agents-md"

describe("bootstrap-agents-md: constants", () => {
  it("MARKER_OPEN ends with the version tag opening so we can stamp versions", () => {
    expect(MARKER_OPEN).toMatch(/^<!-- META-GOVERNOR AUTO-INSTALL SNIPPET \(/)
  })

  it("MARKER_CLOSE is a stable sentinel", () => {
    expect(MARKER_CLOSE).toBe("<!-- END META-GOVERNOR AUTO-INSTALL SNIPPET -->")
  })
})

describe("bootstrap-agents-md: buildSnippet", () => {
  it("stamps the version inside the open marker", () => {
    const s = buildSnippet("0.38.9")
    expect(s).toContain(`${MARKER_OPEN}v0.38.9) -->`)
  })

  it("includes the close marker", () => {
    const s = buildSnippet("0.38.9")
    expect(s).toContain(MARKER_CLOSE)
  })

  it("includes all four [SYSTEM-NUDGE] blocks (Oracle, Lesson Capture, Skill Priming, Sisyphus Protocol)", () => {
    const s = buildSnippet("0.38.9")
    expect(s).toContain("[SYSTEM-NUDGE] Oracle Review Gate")
    expect(s).toContain("[SYSTEM-NUDGE] Lesson Capture")
    expect(s).toContain("[SYSTEM-NUDGE] Skill Priming")
    expect(s).toContain("[SYSTEM-NUDGE] Sisyphus Protocol")
  })

  it("documents the opt-out env var so users know how to disable", () => {
    const s = buildSnippet("0.38.9")
    expect(s).toContain("OMO_META_GOVERNOR_NO_BOOTSTRAP")
  })

  it("is idempotent: two calls with the same version produce identical content", () => {
    const a = buildSnippet("0.38.9")
    const b = buildSnippet("0.38.9")
    expect(a).toBe(b)
  })

  it("different versions produce different markers", () => {
    expect(buildSnippet("0.38.9")).not.toBe(buildSnippet("0.39.0"))
  })
})

describe("bootstrap-agents-md: isInstalled", () => {
  it("returns true when both markers are present", () => {
    const s = buildSnippet("0.38.9")
    expect(isInstalled(s)).toBe(true)
  })

  it("returns false on empty string", () => {
    expect(isInstalled("")).toBe(false)
  })

  it("returns false on plain user content (no markers)", () => {
    expect(isInstalled("# My AGENTS.md\n\nSome user content.\n")).toBe(false)
  })

  it("returns false when only OPEN marker is present (truncated/corrupted)", () => {
    expect(isInstalled(`${MARKER_OPEN}v0.38.9) -->\nbroken`)).toBe(false)
  })

  it("returns false when only CLOSE marker is present (truncated/corrupted)", () => {
    expect(isInstalled(`broken\n${MARKER_CLOSE}`)).toBe(false)
  })
})

describe("bootstrap-agents-md: mergeInto", () => {
  it("creates file with intro + snippet when existing is empty", () => {
    const snippet = buildSnippet("0.38.9")
    const out = mergeInto("", snippet, "0.38.9")
    expect(out).toContain("# Auto-generated by @herjarsa/omo-meta-governor v0.38.9")
    expect(out).toContain(snippet)
  })

  it("preserves existing user content and appends snippet at end", () => {
    const existing = "# My AGENTS.md\n\nPersonal notes.\n"
    const snippet = buildSnippet("0.38.9")
    const out = mergeInto(existing, snippet, "0.38.9")
    expect(out).toContain("Personal notes.")
    expect(out).toContain(snippet)
    // User content must come BEFORE the snippet
    expect(out.indexOf("Personal notes.")).toBeLessThan(out.indexOf(MARKER_OPEN))
  })

  it("is idempotent: returns existing unchanged when snippet already present", () => {
    const snippet = buildSnippet("0.38.9")
    const firstMerge = mergeInto("# user content\n", snippet, "0.38.9")
    const secondMerge = mergeInto(firstMerge, snippet, "0.38.9")
    expect(secondMerge).toBe(firstMerge)
  })

  it("strips trailing whitespace from existing before appending", () => {
    const existing = "user content   \n\n\n"
    const snippet = buildSnippet("0.38.9")
    const out = mergeInto(existing, snippet, "0.38.9")
    // Trailing whitespace (spaces + extra newlines) from input must NOT
    // be preserved verbatim — it should be normalized.
    expect(out).not.toMatch(/user content   \n\n\n/)
    // There must be a clean 2-newline separator between "user content" and
    // the snippet marker.
    const idx = out.indexOf("<!-- META-GOVERNOR")
    const between = out.slice("user content".length, idx)
    expect(between).toBe("\n\n")
  })
})

describe("bootstrap-agents-md: installedVersion", () => {
  it("returns the version stamped in the open marker", () => {
    expect(installedVersion(buildSnippet("0.38.9"))).toBe("0.38.9")
  })

  it("captures full pre-release semver suffix (0.38.9-beta.1)", () => {
    // Simulate a v0.38.9-beta.1 marker by editing the snippet.
    const fake = buildSnippet("0.38.9").replace("v0.38.9", "v0.38.9-beta.1")
    expect(installedVersion(fake)).toBe("0.38.9-beta.1")
  })

  it("returns null when no marker is present", () => {
    expect(installedVersion("# just user content")).toBe(null)
  })
})

describe("bootstrap-agents-md: isInstalled version-aware", () => {
  it("returns true when content has the same version as requested", () => {
    expect(isInstalled(buildSnippet("0.38.9"), "0.38.9")).toBe(true)
  })

  it("returns false when content has a different version", () => {
    expect(isInstalled(buildSnippet("0.38.9"), "0.39.0")).toBe(false)
  })
})

describe("bootstrap-agents-md: stripSnippet", () => {
  it("removes the snippet block and preserves surrounding content", () => {
    const snippet = buildSnippet("0.38.9")
    const content = `# user top\n${snippet}\n# user bottom\n`
    const out = stripSnippet(content)
    expect(out).not.toContain(MARKER_OPEN)
    expect(out).not.toContain(MARKER_CLOSE)
    expect(out).toContain("# user top")
    expect(out).toContain("# user bottom")
  })

  it("returns content unchanged when no marker present", () => {
    expect(stripSnippet("# plain content")).toBe("# plain content")
  })
})

describe("bootstrap-agents-md: mergeInto version-aware", () => {
  it("upgrades v0.38.9 snippet to v0.39.0 (replaces, does not duplicate)", () => {
    const oldSnippet = buildSnippet("0.38.9")
    const newSnippet = buildSnippet("0.39.0")
    const first = mergeInto("# user\n", oldSnippet, "0.38.9")
    const second = mergeInto(first, newSnippet, "0.39.0")
    expect((second.match(/<!-- META-GOVERNOR AUTO-INSTALL SNIPPET/g) ?? []).length).toBe(1)
    expect((second.match(/<!-- END META-GOVERNOR/g) ?? []).length).toBe(1)
    expect(installedVersion(second)).toBe("0.39.0")
    expect(second).toContain("# user")
  })
})
